// Barrido de casos borde (registrado sin direcciones, alta desde el checkout, topes de cantidad, salir).
// Uso: node tests/referencia/barrido-demo.mjs <carpeta-salida>
import { chromium } from 'playwright';
import fs from 'node:fs';
const OUT = process.argv[2] ?? 'capturas-barrido';
fs.mkdirSync(OUT, { recursive: true });
const B = 'http://localhost:5179';
const browser = await chromium.launch();
const p = await browser.newPage({ viewport: { width: 1920, height: 1100 } });
const errores = [];
p.on('pageerror', (e) => errores.push(e.message));
const ok = (t) => console.log('✓', t);
const listo = () => p.getByRole('status').waitFor({ state: 'detached' }).catch(() => {});
await p.goto(B + '/busqueda');
await p.getByRole('button', { name: 'No permitir nunca' }).click();
await listo();
await p.getByRole('button', { name: 'Ingresar' }).click();
await p.getByPlaceholder('Ingresa tu correo electrónico').fill('ernesto@empresa.com.mx');
await p.getByPlaceholder('Ingresa tu contraseña').fill('demo1234');
await p.getByRole('button', { name: 'Iniciar sesión' }).click();
await p.locator('[data-ancla=usuario]').click();
await p.getByRole('navigation', { name: 'Mi cuenta' }).getByText('Mi perfil').click();
await p.getByRole('button', { name: 'Dirección de envío' }).click();
while (await p.getByRole('button', { name: 'Eliminar' }).count()) await p.getByRole('button', { name: 'Eliminar' }).first().click();
await p.getByText('Por el momento no hay direcciones registradas').waitFor();
if (!(await p.getByRole('button', { name: 'Entrega en' }).innerText()).includes('45138')) throw new Error('Sin direcciones la entrega debe volver a 45138');
ok('Eliminar todas las direcciones: la entrega vuelve al C.P. 45138');
await p.getByRole('button', { name: 'Buscar', exact: true }).click();
await listo();
await p.getByRole('button', { name: 'Agregar al carrito' }).first().click();
await p.getByRole('button', { name: 'Ver todos los productos' }).click();
await p.waitForURL('**/carrito');
const mas = p.getByRole('button', { name: 'Agregar uno' }).first();
for (let i = 0; i < 300 && (await mas.isEnabled()); i++) await mas.click();
await p.getByText(/Solo hay \d+ piezas disponibles para compra en línea/).waitFor();
await p.screenshot({ path: `${OUT}/1-carrito-tope.png` });
ok('Carrito: "+" se detiene en el tope con aviso');
await p.getByRole('button', { name: 'Quitar uno' }).first().click();
await p.getByRole('button', { name: 'Proceder al pago' }).first().click();
await p.waitForURL('**/checkout/datos');
await p.getByText('Añade una dirección para enviarte tu pedido').waitFor();
if (await p.getByRole('button', { name: 'Continuar' }).isEnabled()) throw new Error('Continuar sin dirección');
ok('Registrado sin direcciones: va al paso 1 y pide añadir una');
await p.getByRole('button', { name: /Añadir dirección/ }).click();
await p.waitForURL('**/configuracion/direcciones/nueva');
for (const [n, v] of [['nombre', 'Oficina'], ['calle', 'Av. Vallarta'], ['numeroExterior', '3000'], ['entreCalle1', 'Calle A'], ['entreCalle2', 'Calle B'], ['codigoPostal', '45040']])
  await p.locator(`input[name=${n}]`).fill(v);
await p.locator('select[name=colonia]').selectOption({ index: 1 });
await p.getByRole('button', { name: 'Guardar' }).click();
await p.waitForURL('**/checkout/envio');
await p.locator('p', { hasText: /^Oficina$/ }).waitFor();
await p.screenshot({ path: `${OUT}/2-envio-nueva-direccion.png`, fullPage: true });
ok('Alta desde el checkout: regresa al paso 2 con la nueva dirección');
await p.getByRole('button', { name: 'Continuar' }).click();
await p.waitForURL('**/checkout/pago');
await p.getByText(/terminación/).first().click();
await p.getByRole('button', { name: 'Continuar' }).click();
await p.waitForURL('**/checkout/confirmacion');
if (await p.getByText('Envío', { exact: true }).count()) throw new Error('El resumen no debe mostrar la fila Envío');
await p.screenshot({ path: `${OUT}/3-confirmacion.png`, fullPage: true });
await p.getByRole('button', { name: 'Cambiar' }).first().click();
await p.waitForURL('**/checkout/envio');
ok('Confirmación: "Cambiar" (envío) del registrado lleva al paso 2 y el resumen no tiene fila de envío');
await p.goBack();
await p.goto(B + '/producto/alternador-150a').catch(() => {});
console.log('(goto recarga: se reinicia el estado)');
await p.getByRole('button', { name: 'No permitir nunca' }).click().catch(() => {});
await listo();
const masD = p.getByRole('button', { name: 'Agregar uno' });
for (let i = 0; i < 50 && (await masD.isEnabled()); i++) await masD.click();
await p.getByText(/Solo hay \d+ piezas disponibles para compra en línea/).waitFor();
await p.screenshot({ path: `${OUT}/4-detalle-tope.png` });
ok('Detalle: la cantidad se detiene en el tope con aviso');
await browser.close();
if (errores.length) console.log('ERRORES', errores);
console.log('ok', OUT);
