// Capturas de Configuración en la demo (cliente registrado): menú de la cuenta, direcciones, nueva dirección y
// estado vacío. Uso: node tests/referencia/configuracion-demo.mjs <carpeta-salida>
import { chromium } from 'playwright';
import fs from 'node:fs';
const OUT = process.argv[2] ?? 'capturas-configuracion';
fs.mkdirSync(OUT, { recursive: true });
const browser = await chromium.launch();
const errores = [];
const p = await browser.newPage({ viewport: { width: 1920, height: 1100 } });
p.on('pageerror', (e) => errores.push(e.message));
await p.goto('http://localhost:5179/');
await p.getByRole('button', { name: 'No permitir nunca' }).click();
await p.getByRole('button', { name: 'Ingresar' }).click();
await p.getByPlaceholder('Ingresa tu correo electrónico').fill('ernesto@empresa.com.mx');
await p.getByPlaceholder('Ingresa tu contraseña').fill('demo1234');
await p.getByRole('dialog', { name: 'Iniciar sesión' }).getByRole('button', { name: 'Iniciar sesión' }).click();
await p.evaluate(() => document.fonts.ready);
await p.getByRole('button', { name: 'Mi cuenta' }).click();
await p.screenshot({ path: `${OUT}/1-menu-cuenta.png`, clip: { x: 1200, y: 0, width: 720, height: 360 } });
await p.getByRole('navigation', { name: 'Mi cuenta' }).getByText('Mi perfil').click();
await p.getByRole('button', { name: 'Dirección de envío' }).click();
await p.waitForURL('**/configuracion/direcciones');
await p.screenshot({ path: `${OUT}/2-direcciones.png`, fullPage: true });
await p.getByRole('button', { name: 'Nueva dirección' }).click();
await p.waitForURL('**/configuracion/direcciones/nueva');
await p.screenshot({ path: `${OUT}/3-nueva-vacia.png`, fullPage: true });
const f = (n, v) => p.locator(`input[name=${n}]`).fill(v);
await f('nombre', 'Refaccionaria Tesistán');
await f('calle', 'Av. Juan Gil Preciado');
await f('numeroExterior', '4051');
await f('entreCalle1', 'Calle Pino');
await f('entreCalle2', 'Calle Cedro');
await f('codigoPostal', '45138');
await p.getByLabel('Colonia').selectOption('Hogares de Nuevo México');
await p.getByText('Utilizar esta dirección como predeterminada').click();
await p.screenshot({ path: `${OUT}/4-nueva-llena.png`, fullPage: true });
await p.getByRole('button', { name: 'Guardar' }).click();
await p.waitForURL('**/configuracion/direcciones');
console.log('chip:', (await p.getByRole('button', { name: 'Entrega en' }).innerText()).replace(/\n/g, ' '));
await p.screenshot({ path: `${OUT}/5-guardada.png`, fullPage: true });
for (let i = 0; i < 5; i++) await p.getByRole('button', { name: 'Eliminar' }).first().click();
await p.screenshot({ path: `${OUT}/6-vacia.png` });
await browser.close();
if (errores.length) console.log('ERRORES', errores);
console.log('ok', OUT);
