// Recorre el flujo completo de la demo (Autex_2026_Frames): invitado y cliente registrado. Falla si algo no responde.
import { chromium } from 'playwright';
const B = 'http://localhost:5179';
const browser = await chromium.launch();
const errores = [];
async function nueva(opciones = {}) {
  const p = await browser.newPage({ viewport: { width: 1920, height: 1200 }, ...opciones });
  p.on('pageerror', (e) => errores.push(e.message));
  p.on('console', (m) => m.type() === 'error' && errores.push(m.text()));
  return p;
}
const paso = (t) => console.log('✓', t);
/* Resultados (D36): esperar a que termine "Cargando productos…". */
const productosCargados = async (p) => {
  await p.getByRole('status', { name: 'Cargando productos…' }).waitFor({ timeout: 1500 }).catch(() => {});
  await p.getByRole('status', { name: 'Cargando productos…' }).waitFor({ state: 'detached' });
};
/* Al entrar aparece el aviso (simulado) del navegador; al cerrarlo aparece el de Autex "Elige una tienda". */
async function cerrarAviso(p) {
  await p.getByRole('button', { name: 'Cerrar aviso de ubicación' }).click();
  const aviso = p.getByRole('dialog', { name: 'Elige una tienda' });
  await aviso.waitFor();
  await aviso.getByRole('button', { name: 'Cerrar' }).click();
}

// 0) Páginas del sitio real (autex.com.mx) sin respaldo en Figma
let p = await nueva();
await p.goto(B + '/');
await cerrarAviso(p);
paso('Al entrar sale el aviso del navegador; al cerrarlo, el de Autex "Elige una tienda"');
await p.getByText('Explora por especialidad').waitFor();
await p.getByRole('link', { name: 'Catálogo', exact: true }).click();
await p.getByText('Catálogo de productos').waitFor();
await p.getByRole('link', { name: 'Refacciones de iluminacion' }).click();
await p.waitForURL('**/busqueda?**');
await productosCargados(p);
if ((await p.getByRole('button', { name: /Agregar a lista/ }).count()) !== 4) throw new Error('El filtro por categoría no dejó 4 productos');
paso('Inicio → Catálogo → categoría: ventana "Cargando productos…" y la búsqueda filtrada');
await p.getByRole('link', { name: 'Marcas', exact: true }).click();
await p.getByPlaceholder('Buscar por nombre de la marca').fill('tecno');
await p.getByRole('link', { name: 'TECNOFUEL', exact: true }).click();
await p.waitForURL('**/busqueda?marca=**');
paso('Búsqueda por marca → resultados de la marca');
await p.getByPlaceholder('Buscar marca, modelo, tipo de producto...').fill('zzz');
await p.getByRole('button', { name: 'Buscar', exact: true }).click();
await p.getByText('"Tu búsqueda no coincidió con ningún producto"').waitFor();
paso('Buscador del navbar: sin resultados muestra el estado vacío');
for (const [esp, producto] of [['Ferreteria', 'Cinta aislante de vinil negra 19 mm x 18 m'], ['Herramientas y equipos', 'Faro de trabajo LED redondo 27W 12/24V'], ['Motocicletas', 'Bujía Autolite Xtreme Sport Iridium para motocicleta'], ['Seguridad y prevencion', 'Chaleco de seguridad reflejante naranja talla única']]) {
  await p.goto(B + `/busqueda?especialidad=${encodeURIComponent(esp)}`);
  await cerrarAviso(p);
  await productosCargados(p);
  await p.getByRole('button', { name: producto }).first().waitFor();
}
paso('Catálogo con las 5 especialidades (cinta aislante, faro LED, bujía de moto, chaleco…)');
await p.goto(B + '/busqueda?q=bateria');
await cerrarAviso(p);
await productosCargados(p);
if ((await p.getByRole('button', { name: /Agregar a lista/ }).count()) !== 2) throw new Error('Con C.P. 45138 deben verse las 2 baterías (sucursales locales)');
await p.getByRole('button', { name: 'Entrega en' }).click();
await p.getByPlaceholder('Ingresa un código postal mexicano').fill('98000');
await p.getByRole('button', { name: 'Actualizar ubicación' }).click();
await p.getByRole('dialog', { name: 'Selecciona una tienda' }).waitFor();
await p.getByRole('dialog', { name: 'Selecciona una tienda' }).getByRole('button', { name: 'Cerrar' }).click();
if ((await p.getByRole('button', { name: /Agregar a lista/ }).count()) !== 0) throw new Error('Con C.P. 98000 (Zacatecas) las baterías no tienen sucursal local y deben ocultarse');
paso('Baterías: solo existencias locales/local extendido (45138 sí, 98000 Zacatecas no)');
await p.goto(B + '/sucursales');
await cerrarAviso(p);
await p.getByPlaceholder('Buscar por Estado, Ciudad, CP').fill('Jalisco');
await p.getByText(/^\d+ sucursales/).first().waitFor();
await p.goto(B + '/como-comprar');
await cerrarAviso(p);
await p.getByText('Compra en Autex fácil y seguro').waitFor();
await p.goto(B + '/ofertas');
await cerrarAviso(p);
await p.getByRole('heading', { name: 'Ofertas' }).waitFor();
paso('Sucursales, Cómo comprar y Ofertas cargan');
await p.close();

// 1) Invitado · tarjeta nueva
p = await nueva();
await p.goto(B + '/busqueda');
await p.getByRole('button', { name: 'No permitir nunca' }).click();
await p.waitForTimeout(300);
if (await p.getByRole('dialog', { name: 'Elige una tienda' }).count()) throw new Error('"No permitir nunca" solo debe cerrar el aviso');
paso('"No permitir nunca" solo cierra el aviso del navegador (sin "Elige una tienda")');
if (!(await p.getByRole('button', { name: 'Entrega en' }).innerText()).includes('45138')) throw new Error('La entrega predeterminada no es 45138');
if (!(await p.getByRole('button', { name: 'Mi tienda' }).innerText()).includes('Tesistan')) throw new Error('La tienda predeterminada no es Tesistán');
if ((await p.getByRole('button', { name: 'Mis vehículos' }).innerText()).trim() !== 'directions_car_filled\nMis vehículos') throw new Error('No debe haber vehículo al entrar');
paso('Sin ubicación: entrega 45138, tienda Tesistán y sin vehículo');
await p.getByRole('button', { name: 'Entrega en' }).click();
await p.getByRole('button', { name: 'Usar mi ubicación actual' }).click();
await p.getByText('No tenemos permiso para conocer tu ubicación').waitFor();
paso('"No permitir nunca": "Usar mi ubicación actual" ya no vuelve a preguntar');
await p.getByPlaceholder('Ingresa un código postal mexicano').fill('44400');
await p.getByRole('button', { name: 'Actualizar ubicación' }).click();
await p.getByRole('status', { name: 'Actualizando tu ubicación' }).waitFor();
const panel = p.getByRole('dialog', { name: 'Selecciona una tienda' });
await panel.getByText('Envío Local').first().waitFor();
await panel.getByRole('button', { name: 'Seleccionar tienda' }).first().click();
await p.getByRole('status', { name: 'Cambiando tu tienda' }).waitFor();
await p.getByRole('status', { name: 'Cambiando tu tienda' }).waitFor({ state: 'detached' });
if (!(await p.getByRole('button', { name: 'Entrega en' }).innerText()).includes('44400')) throw new Error('No cambió la entrega');
paso('"Elegir tienda manualmente" pide el C.P. y muestra las tiendas de ese estado (con ventanas de carga al cambiar C.P. y tienda)');
await p.getByRole('button', { name: 'Mis vehículos' }).click();
await p.getByText('No has seleccionado ningún vehículo').waitFor();
await p.getByLabel('Año', { exact: true }).last().selectOption('2014');
await p.getByLabel('Marca', { exact: true }).last().selectOption('Chevrolet');
await p.getByLabel('Modelo', { exact: true }).last().selectOption('Aveo');
await p.getByRole('button', { name: 'Agregar vehículo a la lista' }).click();
await p.getByRole('button', { name: 'Activar navegación sin vehículo' }).waitFor();
await p.getByRole('dialog', { name: 'Mis vehículos' }).getByRole('button', { name: 'Cerrar' }).click();
await p.getByText('Chevrolet Aveo 2014').waitFor();
paso('Mis vehículos: agregar un vehículo lo activa ("Buscando para Chevrolet Aveo 2014")');
await p.getByRole('status', { name: 'Cargando productos…' }).waitFor({ state: 'detached' });
if ((await p.getByRole('button', { name: 'Avisar disponibilidad' }).count()) !== 0) throw new Error('Los productos sin existencia deben ocultarse');
if (!(await p.getByText('+100 pzs').count())) throw new Error('Falta la etiqueta de existencia "+100 pzs"');
await p.getByText(/Mostrar productos no disponibles/).click();
await productosCargados(p);
if ((await p.getByRole('button', { name: 'Avisar disponibilidad' }).count()) < 1) throw new Error('Falta "Avisar disponibilidad" en productos sin existencia');
await p.getByText(/Mostrar productos no disponibles/).click();
paso('Catálogo: oculta lo que no tiene existencia (filtro para verlo, "Avisar disponibilidad") y etiqueta "+100 pzs"');
const cant = p.getByLabel('Cantidad de Alternador 12V 150A alto rendimiento Tecnofuel');
await cant.fill('50');
await cant.press('Enter');
if ((await cant.inputValue()) !== '11') throw new Error('La cantidad debe ajustarse a las 11 piezas disponibles en línea');
await p.getByText('Solo hay 11 piezas disponibles para compra en línea.').waitFor();
await cant.fill('2');
await cant.press('Enter');
paso('Tarjeta: la cantidad se escribe y no supera la existencia para venta en línea (50 → 11 con aviso)');
await p.getByRole('button', { name: 'Agregar al carrito' }).first().click();
await p.getByRole('dialog', { name: 'Mi carrito' }).waitFor();
paso('Agregar abre el mini-carrito');
await p.getByRole('button', { name: 'Ver todos los productos' }).click();
await p.waitForURL('**/carrito');
await p.getByText('Productos disponibles (1)').waitFor();
await p.getByRole('button', { name: 'Proceder al pago' }).first().click();
const como = p.getByRole('dialog', { name: '¿Cómo deseas continuar?' });
await como.waitFor();
if (await como.getByRole('button', { name: 'Aceptar' }).isEnabled()) throw new Error('"Aceptar" debe esperar a que se elija una opción');
await como.getByRole('radio', { name: 'Usuario invitado' }).click();
await como.getByRole('button', { name: 'Aceptar' }).click();
paso('Carrito (invitado): "Proceder al pago" pregunta "¿Cómo deseas continuar?" → Usuario invitado');
await p.waitForURL('**/checkout/datos');
await p.getByText('Usuario Invitado').waitFor();
const continuar = p.getByRole('button', { name: 'Continuar' });
if (await continuar.isEnabled()) throw new Error('"Continuar" debe esperar a que el formulario esté completo');
for (const [n, v] of [['nombre', 'Ana'], ['apellido', 'López Pérez'], ['correo', 'ana@correo.com'], ['telefono', '3312345678'], ['calle', 'Av. Juárez'], ['numeroExterior', '120'], ['entreCalle1', 'Calle 8 de Julio'], ['entreCalle2', 'Calle Colón'], ['codigoPostal', '44100']])
  await p.locator(`input[name=${n}]`).fill(v);
if ((await p.getByLabel('Estado').inputValue()) !== 'Jalisco') throw new Error('El estado no se llenó con el C.P.');
await p.locator('select[name=colonia]').selectOption({ index: 1 });
await continuar.click();
await p.waitForURL('**/checkout/envio');
await p.getByText(/Av\. Juárez 120/).first().waitFor();
paso('Invitado: formulario de autex.com.mx (cliente, fiscales y dirección con colonia por C.P.) → paso 2 con su dirección');
await p.getByText('(Entrega inmediata)').waitFor();
await p.getByRole('button', { name: 'Continuar' }).click();
await p.waitForURL('**/checkout/pago');
paso('Invitado: datos → envío (entrega inmediata) → pago');
await p.getByRole('button', { name: 'Regresar' }).click();
await p.waitForURL('**/checkout/envio');
await p.getByRole('button', { name: 'Regresar' }).click();
await p.waitForURL('**/checkout/datos');
if ((await p.locator('input[name=calle]').inputValue()) !== 'Av. Juárez') throw new Error('Al regresar, el formulario del invitado debe conservar sus datos');
await p.getByRole('button', { name: 'Continuar' }).click();
await p.waitForURL('**/checkout/envio');
await p.getByRole('button', { name: 'Continuar' }).click();
await p.waitForURL('**/checkout/pago');
paso('Invitado: al regresar del paso 2 el formulario conserva lo capturado');
if ((await p.getByLabel('Nombre del titular').inputValue()) !== 'Ana López Pérez') throw new Error('La tarjeta del invitado debe empezar vacía con su nombre como titular');
if (await p.getByRole('button', { name: 'Continuar' }).isEnabled()) throw new Error('"Continuar" debe esperar a la tarjeta completa');
await p.getByLabel('Número de tarjeta').fill('4111 1111 1111 1111');
await p.getByLabel('Vigencia').fill('1228');
await p.getByLabel('CVV').fill('123');
if ((await p.getByLabel('Vigencia').inputValue()) !== '12/28') throw new Error('La vigencia debe quedar como MM/AA');
paso('Invitado: tarjeta vacía con su nombre, validada (número, MM/AA, CVV)');
await p.getByRole('button', { name: 'Continuar' }).click();
await p.waitForURL('**/checkout/confirmacion');
await p.getByText('Visa terminación 1111').waitFor();
await p.getByText('#0001087 - 24').first().waitFor();
await p.getByRole('button', { name: 'Confirmar el pedido' }).click();
await p.getByRole('button', { name: 'Pagar' }).click();
await p.getByText('Verificando tus datos').waitFor();
await p.waitForURL('**/checkout/gracias', { timeout: 5000 });
await p.getByText('¡Muchas gracias por tu compra!').waitFor();
await p.getByText('#0001087 - 24.').waitFor();
paso('Invitado: confirmación → OpenPay → verificando → gracias (pedido #0001087)');
await p.close();

// 2) Cliente registrado · producto bajo pedido · tarjeta guardada · con permiso de ubicación (no sale el aviso)
p = await nueva();
await p.goto(B + '/busqueda');
await p.getByRole('button', { name: 'Permitir esta vez' }).click();
await p.getByRole('status', { name: 'Ubicando tu tienda más cercana' }).waitFor();
await p.getByRole('button', { name: 'Mi tienda' }).getByText('Autex Federalismo').waitFor();
if (await p.getByRole('dialog', { name: 'Elige una tienda' }).count()) throw new Error('Con permiso no debe salir el aviso');
paso('Con permiso de ubicación: Mi tienda es la más cercana y no sale el aviso de Autex');
await p.getByRole('button', { name: 'Ingresar' }).click();
await p.getByPlaceholder('Ingresa tu correo electrónico').fill('ernesto@empresa.com.mx');
await p.getByPlaceholder('Ingresa tu contraseña').fill('demo1234');
await p.getByRole('button', { name: 'Iniciar sesión' }).click();
await p.getByText('Hola', { exact: true }).waitFor();
paso('Registrado: inicio de sesión simulado desde el navbar');
await p.getByRole('button', { name: 'Entrega en' }).getByText('Taller Chapalita').waitFor();
paso('Registrado: la entrega pasa a su dirección predeterminada (Taller Chapalita, 45040)');
await p.getByRole('button', { name: 'Entrega en' }).click();
await p.getByText('Mis direcciones').waitFor();
await p.getByText('Casa', { exact: true }).click();
await p.getByRole('dialog', { name: 'Selecciona una tienda' }).getByText('Mi tienda').waitFor();
await p.getByRole('dialog', { name: 'Selecciona una tienda' }).getByRole('button', { name: 'Cerrar' }).click();
if (!(await p.getByRole('button', { name: 'Entrega en' }).innerText()).includes('44260')) throw new Error('No cambió a la dirección "Casa"');
paso('Registrado: elige otra dirección guardada y se muestran las tiendas de su zona');
await p.getByRole('button', { name: 'Mi cuenta' }).click();
await p.getByRole('navigation', { name: 'Mi cuenta' }).getByText('Mi perfil').click();
await p.getByRole('button', { name: 'Dirección de envío' }).click();
await p.getByRole('button', { name: 'Nueva dirección' }).click();
for (const [n, v] of [['nombre', 'Refaccionaria Tesistán'], ['calle', 'Av. Juan Gil Preciado'], ['numeroExterior', '4051'], ['entreCalle1', 'Calle Pino'], ['entreCalle2', 'Calle Cedro'], ['codigoPostal', '45138']])
  await p.locator(`input[name=${n}]`).fill(v);
if ((await p.getByLabel('Estado').inputValue()) !== 'Jalisco') throw new Error('El estado no se llenó con el C.P.');
await p.getByLabel('Colonia').selectOption('Hogares de Nuevo México');
await p.getByText('Utilizar esta dirección como predeterminada').click();
await p.getByRole('button', { name: 'Guardar' }).click();
await p.getByText('Mis direcciones (5)').waitFor();
await p.getByRole('button', { name: 'Entrega en' }).getByText('Refaccionaria Tesistán').waitFor();
paso('Registrado: Mi perfil → Dirección de envío → Nueva dirección (colonia por C.P.) y queda como entrega predeterminada');
await p.getByRole('button', { name: 'Buscar', exact: true }).click();
await p.waitForURL('**/busqueda');
const mini = p.getByRole('dialog', { name: 'Mi carrito' });
for (const i of [0, 1]) {
  await p.getByRole('button', { name: 'Agregar al carrito' }).nth(i).click(); // inyector y cuerpo de aceleración
  await mini.getByRole('button', { name: 'Cerrar' }).click();
}
await p.getByRole('button', { name: 'Agregar al carrito' }).nth(2).click(); // filtro de aire: solo en CEDIS
await mini.getByRole('button', { name: 'Cerrar' }).click();
/* Motoventilador: Tesistán no lo tiene, sale de otra sucursal (envío aparte). */
await p.getByLabel('Cantidad de Motoventilador de radiador Tecnofuel').locator('xpath=ancestor::*[.//button[normalize-space()="Agregar al carrito"]][1]').getByRole('button', { name: 'Agregar al carrito' }).click();
await p.getByRole('button', { name: 'Ver todos los productos' }).click();
await p.waitForURL('**/carrito');
await p.getByText('Productos bajo pedido (1)').waitFor();
paso('Carrito: el producto que solo tiene CEDIS 41 aparece como "bajo pedido"');
await p.getByRole('button', { name: 'Proceder al pago' }).first().click();
await p.getByRole('status', { name: 'Preparando tu pedido' }).waitFor();
await p.waitForURL('**/checkout/envio');
paso('Registrado: "Proceder al pago" pasa directo al paso 2 (ya tiene dirección predeterminada)');
await p.getByText('Dirección de entrega', { exact: true }).waitFor();
await p.locator('p', { hasText: /^Refaccionaria Tesistán$/ }).waitFor();
if (await p.getByText('Sin costo de envío').count()) throw new Error('El paso 2 no debe mostrar costo de envío');
await p.getByText('Tu pedido llegará en').getByText('3 envíos').waitFor();
for (const n of [1, 2, 3]) await p.getByRole('button', { name: new RegExp(`Envío ${n}`) }).waitFor();
await p.getByRole('button', { name: /Envío 1/ }).click();
await p.getByText(/Sale de Autex/).first().waitFor();
if (await p.getByText(/Sale de CEDIS/).count()) throw new Error('CEDIS no debe ser origen de envío');
paso('Paso 2: dirección visible, sin costos y 3 envíos reales (Tesistán, otra sucursal con lo que Tesistán no tiene y lo bajo pedido)');
await p.getByRole('button', { name: 'Cambiar dirección de entrega' }).hover();
await p.getByRole('tooltip').getByText(/podría verse afectado/).waitFor({ state: 'visible' });
await p.getByRole('button', { name: 'Cambiar dirección de entrega' }).click();
const modal = p.getByRole('dialog', { name: 'Cambiar dirección de entrega' });
await modal.getByText('Casa', { exact: true }).click();
await modal.getByRole('button', { name: 'Usar esta dirección' }).click();
await p.locator('p', { hasText: /^Casa$/ }).waitFor();
paso('Paso 2: "Cambiar dirección de entrega" (con aviso) cambia la dirección sin volver a datos del usuario');
await p.getByText('(Productos bajo pedido)').waitFor();
await p.getByRole('button', { name: 'Continuar' }).click();
await p.waitForURL('**/checkout/pago');
await p.getByText('Mastercard con terminación 5517').click();
await p.getByRole('button', { name: 'Continuar' }).click();
await p.waitForURL('**/checkout/confirmacion');
await p.getByText('Mastercard terminación 5517').waitFor();
await p.getByText('Ernesto Quiñonez / Taller Chapalita').waitFor();
await p.getByText(/Calz del Federalismo Nte 1343/).first().waitFor();
paso('Registrado: envío → tarjeta guardada → confirmación con la dirección elegida');
await p.getByRole('button', { name: 'Confirmar el pedido' }).click();
await p.getByRole('button', { name: 'Pagar' }).click();
await p.waitForURL('**/checkout/gracias', { timeout: 5000 });
await p.getByText('#0001087 - 24.').waitFor();
await p.getByRole('button', { name: 'Seguir comprando' }).click();
await p.waitForURL(B + '/');
await p.locator('[data-ancla=usuario]').click();
await p.getByRole('navigation', { name: 'Mi cuenta' }).getByRole('button', { name: 'Mis pedidos' }).click();
await p.getByText('Pedido #0001087 - 24').waitFor();
await p.getByText(/En preparación/).waitFor();
paso('Registrado: "Seguir comprando" conserva la sesión y el pedido aparece en Mis pedidos');
await p.close();

await browser.close();
if (errores.length) {
  console.log('ERRORES DE CONSOLA:\n' + [...new Set(errores)].join('\n'));
  process.exit(1);
}
console.log('Flujo completo sin errores');
